name: Builds docker image
description: Builds docker image

inputs:
  dockerfile:
    description: Dockerfile filename
    default: Dockerfile
    required: false
  repository:
    description: ECR repository name
    required: true
  aws-access-key-id:
    description: AWS Access key ID
    required: true
  aws-secret-access-key:
    description: AWS Secret access key
    required: true
  aws-region:
    description: AWS region
    required: true
  ecr-registry:
    description: ECR registry
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      shell: bash
      run: |
        cd backend
        docker build -t "${{ inputs.ecr-registry }}/${{ inputs.repository }}:${{ github.sha }}" -f ${{ inputs.dockerfile }} .
        # docker push "${{ inputs.ecr-registry }}/${{ inputs.repository }}:${{ github.sha }}"
        echo "::set-output name=image::${{ inputs.ecr-registry }}/${{ inputs.repository }}:${{ github.sha }}"
