name: Deploy to AWS

on:
  push:
    tags:
      - DEPLOY-*

concurrency: deploy_env

jobs:
  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/build-docker
        name: build-backend
        with:
          repository: ${{secrets.ECR_REPOSITORY}}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          ecr-registry: ${{secrets.ECR_REGISTRY}}
